### ISSUE TITLE
`New{{classname}}WithDefaults` functions... do we want them?

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault-client-go#194]
Currently, for every model struct, we generate a `New{{classname}}WithDefaults` function.

For `Response` models... this seems trivially unnecessary, as response models only exist to deserialize data from the server.

For `Request` models... I wonder if this is **also** unnecessary, because:

* All of the default values that we know about, are declared in the OpenAPI

* They are declared in the OpenAPI, because they are defined as defaults in `sdk/framework.Path` structs

* The Vault server request handling code is going to automatically apply these defaults, when the given parameters are absent from requests sent over the network

* So what is the point in providing extra methods which help clients of the API fill in the very same defaults the server side is going to fill in anyway?

Unless I'm missing something here, I wonder if we might just delete this chunk of the template entirely:

https://github.com/hashicorp/vault-client-go/blob/21d51ea1c54800bd4579fea8ab0f5bf26cf62a4e/generate/templates/model_simple.handlebars#L23-L33

**Comment by averche** [comment]
`NewXWithDefaults()` is a remnant of the original code-generation templates from openapi-generator. I've been thinking about removing these, especially since they don't play well with the request method signatures which accept the request body objects by value rather than by pointer. Side note: I'm still wondering whether we should accept _Request objects by pointer instead.

>  - The Vault server request handling code is going to automatically apply these defaults, when the given parameters are absent from requests sent over the network

I think this is a very good argument in favour of removing these. If anything, it adds to more confusion if we keep these.
