### ISSUE TITLE
KvV1Write, CubbyholeWrite, System.Wrap are unusable

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault-client-go#201]
# Expected Behavior

Functions mapping a Vault API that takes arbitrary input, such as:
- POST kv-v1/{path}
- POST cubbyhole/{path}
- POST sys/wrapping/wrap

should have a `map[string]interface{}` parameter to specify the request body.

# Current Behavior

Functions are useless, as they do not permit specifying the request body at all!

# Additional Information

This is a bit of a challenge, as AFAIK, the OpenAPI spec doesn't actually provide a way to define an API like this. An ad-hoc Vault-specific extension may be needed.

**Comment by averche** [comment]
KV-v1 is probably the biggest concern here, since `cubbyhole/{path}` and `sys/wrapping/wrap` are not often accessed directly.

> This is a bit of a challenge, as AFAIK, the OpenAPI spec doesn't actually provide a way to define an API like this. An ad-hoc Vault-specific extension may be needed.

Perhaps we can generate something like [this](https://github.com/hashicorp/vault-client-go/blob/252790aa241a30516d2e3e184a57da02a6024e87/openapi.json#L36004-L36008) at the request level instead of a named request object for anything that takes an arbitrary input:

```json
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "data": {
                  "type": "object",
                  "format": "map"
                }
              }
            }
          }
        }

```

**Comment by maxb** [comment]
These now all work correctly.

**Comment by averche** [comment]
Thank you very much for fixing these!
