### ISSUE TITLE
Generic Methods always use a `/v1/` prefix

### ISSUE THREAD

**Issue by iuliancristea** [hashicorp/vault-client-go#240]
# Expected Behavior

According to the docs, with generic methods, it should be possible to run operations for KV v2 paths.

# Current Behavior

The generic methods always prefix the path with `/v1/` before sending the requests.

# Failure Information

`vault-client-go` => `v0.4.0`

## Steps to Reproduce

Not required. Every generic method has a call to the `v1Path` method. Example https://github.com/hashicorp/vault-client-go/blob/main/client_requests.go#L30

**Comment by averche** [comment]
Hi @iuliancristea and thanks for checking out the library!

Currently, every API path in Vault is rooted at `/v1`, including the [KV-v2 paths](https://github.com/hashicorp/vault-client-go/blob/fd98162630955fc3bcf963e725733903102a8787/api_secrets.go#L3055). The naming is very confusing but, the "v2" in KV-v2 refers to the new version of KV secrets engine rather than a new version of the API.

The generic `Read`/`Write`/`List`/`Delete` methods are based on the old library's `client.Logical().Read`/`Write`/`List`/`Delete` methods respectively which also automatically [appends the `/v1` prefix](https://github.com/hashicorp/vault/blob/32059ab2505b29e2d82507a27150cc85000db770/api/logical.go#L144). In the new library, we append it only if not provided (e.g. `Read(ctx, "/v1/some/path")` is equivalent to `Read("/some/path")). This logic should help with any migrations from the old library to the new one.

In the future, if/when the `/v2` version of the API is released, my thinking is we can adjust the logic to default to `/v1` prefix *unless* the provided path begins with `/v{d+}/`.

P.S. If you are using the library to read KV-v2 secrets, I'd recommend using the generated method instead:

```go
	// read a secret
	s, err := client.Secrets.KvV2Read(ctx, "foo", vault.WithMountPath("secret"))
	if err != nil {
		// handle err
	}
	log.Println("secret retrieved:", s.Data.Data)
```

**Comment by averche** [comment]
Going to close this issue per above, please feel free to reopen if you still think this is a problem :)
