### ISSUE TITLE
How to do equivalent of `vault login -address "www.x.com" -method oidc`?

### ISSUE THREAD

**Issue by doivosevic** [hashicorp/vault-client-go#244]
I apologize if the question is of low quality but I've spent too much time already trying to figure this out. I just can't for the life of me get the same behavior through my Go code and I can't find any docs about this. Is this a supported scenario? Seems quite simple to me.

**Comment by averche** [comment]
Hi @doivosevic and sorry for the late reply.

I might be mistaken, but looking at the [Vault's OIDC documentation](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth), `vault login -address "www.x.com" -method oidc` does not seem like a correct way to authenticate. I believe the `-address` in this is supposed to refer to the Vault's address rather than the external OIDC provider. Instead, the provider is configured with something like the following ahead of the login:

```shell
vault write auth/oidc/config \
         oidc_discovery_url="https://$AUTH0_DOMAIN/" \
         oidc_client_id="$AUTH0_CLIENT_ID" \
         oidc_client_secret="$AUTH0_CLIENT_SECRET" \
         default_role="reader"

vault write auth/oidc/role/reader \
      bound_audiences="$AUTH0_CLIENT_ID" \
      allowed_redirect_uris="http://localhost:8200/ui/vault/auth/oidc/oidc/callback" \
      allowed_redirect_uris="http://localhost:8250/oidc/callback" \
      user_claim="sub" \
      token_policies="reader"
```

Once fully configured, to begin the OIDC auth flow, I believe you need to call the following:

```go
        resp, err := client.Auth.JwtOidcRequestAuthorizationUrl(
                context.Background(),
                schema.JwtOidcRequestAuthorizationUrlRequest{
                        RedirectUri: "...",
                        Role:        "...",
                },
                vault.WithMountPath("oidc"), // or wherever the plugin is mounted
        )
```

This should return the auth URL, which starts the login flow.

**Comment by averche** [comment]
Closing this per above, please feel free to reopen the ticket if you are still having issues with OIDC.

**Comment by aanderse** [comment]
Hi @averche I have the same question.

I have a fully configured `vault` server which I can use `vault login -method=oidc` on and everything is great... the OIDC auth "flow" is started and on my local machine the `vault` process binds to `localhost:8250`, I get a link to `accounts.google.com/...`, all good.

From there I write some basic code like you have above to begin the OIDC auth "flow", but in my `go` program instead of the `vault` program. Specifically, from your code above I have a `resp` object which contains an `auth_url` value (in a map) that is a link to `accounts.google.com/....` - the url I mention above, which I am supposed to click on and authenticate against google - seems promising, right?
Unfortunately this is where I get lost. If I click on that url nothing will happen because I notice that my `go` program is not binding to `localhost:8250`, [as it should be](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/c0d522986601f6829d50a6d59dbb57589e6c3f86/cli.go#L149). So am I missing some code? Or maybe there is additional configuration you have not included in your example?

Any and all help would be greatly appreciated. Thank you! :bowing_man:.
